# Kafka Config
kafka.bootstrap.servers=192.168.83.129:9092
kafka.topic=log_topic
kafka.group.id=spark_app_group

# MySQL Config
jdbc.url=jdbc:mysql://localhost:3306/bigdata?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
jdbc.user=root
jdbc.password=hadoop
jdbc.table.hot=hot_stats

# HBase Config
hbase.zookeeper.quorum=192.168.83.129,192.168.83.130,192.168.83.131
hbase.zookeeper.property.clientPort=2181
hbase.table.raw=raw_logs
